const productdetailActionTypes = {
   PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
   PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',
   PRODUCT_DETAIL_FAIL: 'PRODUCT_DETAIL_FAIL',
};

export default productdetailActionTypes;
