const adminactionTypes = {
    ADMIN_SIGNIN_REQUEST: 'ADMIN_SIGNIN_REQUEST',
    ADMIN_SIGNIN_SUCCESS: 'ADMIN_SIGNIN_SUCCESS',
    ADMIN_SIGNIN_FAILURE: 'ADMIN_SIGNIN_FAILURE',

    ADMIN_SIGNUP_REQUEST: 'ADMIN_SIGNUP_REQUEST',
    ADMIN_SIGNUP_SUCCESS: 'ADMIN_SIGNUP_SUCCESS',
    ADMIN_SIGNUP_FAILURE: 'ADMIN_SIGNUP_FAILURE',

    ADMIN_DETAIL_REQUEST: 'ADMIN_DETAIL_REQUEST',
    ADMIN_DETAIL_SUCCESS: 'ADMIN_DETAIL_SUCCESS',
    ADMIN_DETAIL_FAILURE: 'ADMIN_DETAIL_FAILURE',
    ADMIN_DETAIL_RESET: 'ADMIN_DETAIL_RESET',

    ADMIN_UPDATE_PROFILE_REQUEST: 'ADMIN_UPDATE_PROFILE_REQUEST',
    ADMIN_UPDATE_PROFILE_SUCCESS: 'ADMIN_UPDATE_PROFILE_SUCCESS',
    ADMIN_UPDATE_PROFILE_FAILURE: 'ADMIN_UPDATE_PROFILE_FAILURE',
    ADMIN_UPDATE_PROFILE_RESET: 'ADMIN_UPDATE_PROFILE_RESET',

    GET_USER_DETAIL_REQUEST: 'GET_USER_DETAIL_REQUEST',
    GET_USER_DETAIL_SUCCESS: 'GET_USER_DETAIL_SUCCESS',
    GET_USER_DETAIL_FAILURE: 'GET_USER_DETAIL_FAILURE',

    ADMIN_SIGNOUT: 'ADMIN_SIGNOUT',
}

export default adminactionTypes
