const useractionTypes = {
    USER_SIGNIN_REQUEST: 'USER_SIGNIN_REQUEST',
    USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
    USER_SIGNIN_FAILURE: 'USER_SIGNIN_FAILURE',

    USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',

    USER_DETAIL_REQUEST: 'USER_DETAIL_REQUEST',
    USER_DETAIL_SUCCESS: 'USER_DETAIL_SUCCESS',
    USER_DETAIL_FAILURE: 'USER_DETAIL_FAILURE',
    USER_DETAIL_RESET: 'USER_DETAIL_RESET',

    USER_UPDATE_PROFILE_REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
    USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
    USER_UPDATE_PROFILE_FAILURE: 'USER_UPDATE_PROFILE_FAILURE',
    USER_UPDATE_PROFILE_RESET: 'USER_UPDATE_PROFILE_RESET',

    USER_SIGNOUT: 'USER_SIGNOUT',
}

export default useractionTypes
